### ISSUE TITLE
Unable to use screen sharing plugin in Chrome

### ISSUE THREAD

**Issue by michzimny** [up2university/multiparty-meeting#1] opened 2019-01-30 12:25 UTC
The screen sharing button in Chrome is not clickable, and there is no way to figure out how to reach a plugin that is needed.

CC @andreacorleto

**Comment by misi** [comment] 2019-02-05 18:59
@michzimny  screen sharing changed radically. Development needed..

**Comment by misi** [comment] 2019-02-05 19:23
It is under development.
https://github.com/havfo/multiparty-meeting/commit/6acd176df15d7df840a27dcfb21400fe03a9c1c8

Is it still an issue? It works fine for me with the latest image..
If it is solved close the issue or give me the detailed way how I can reproduce it. Thx.

**Comment by michzimny** [comment] 2019-02-06 10:55
I have the latest image and the button is still not clickable in Chrome. Please try at:
https://meetings.test.up2university.eu/
![capture](https://user-images.githubusercontent.com/1483196/52336756-072beb80-2a06-11e9-811a-c7d2e389dcb1.PNG)

**Comment by misi** [comment] 2019-02-06 11:47
May I already had the plugin..
Thanks I will check it..

**Comment by misi** [comment] 2019-02-26 12:52
Havar said that the plugin is required for older chrome browsers. 
I guess it is not yet removed because of this, but it will be removed later. 
(Of course it could be handled by versions..)

**Comment by michzimny** [comment] 2019-02-27 10:08
So, is it possible to share screen in newer chrome browsers? And how?

**Comment by misi** [comment] 2020-03-09 13:28
@michzimny  I think we can share window in chrome and firefox so I think this problem not an issue anymore. Please reopen it if there are unanswered questions..

**Closed as completed by misi** 2020-03-09 13:28 UTC
Labels: bug
